clc; clear all; close all;
%%
% s = tf('s');
% C = 100 / (s+30);
% figure();
% margin(C);
% [Gm, Pm, s_, Wcp] = margin(C);
% C1 = exp(-s*Pm * pi * Wcp/ 180) * C;
% figure();
% margin(C1);
img = im2double(imread('pic.png'));
% img = rgb2gray(img);
r = img(:,:,1);
g = img(:,:,2);
b = img(:,:,3);
figure();
imshow(img);
im = zeros(size(img));
[u s v] = svd(r);
k = 3;
Ak = u(:,1:k)*s(1:k,1:k)*v(:,1:k)';
disp(norm(r - Ak));
im(:,:,1) = Ak;
[u s v] = svd(g);
Ak = u(:,1:k)*s(1:k,1:k)*v(:,1:k)';
disp(norm(g - Ak));
im(:,:,2) = Ak;
[u s v] = svd(b);
Ak = u(:,1:k)*s(1:k,1:k)*v(:,1:k)';
disp(norm(b - Ak));
im(:,:,3) = Ak;
figure();
imshow(im);